[2022-12-11T07:42:49.351+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-12-11T07:42:35.121505+00:00 [queued]>
[2022-12-11T07:42:49.529+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-12-11T07:42:35.121505+00:00 [queued]>
[2022-12-11T07:42:49.537+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T07:42:49.541+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-12-11T07:42:49.544+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-12-11T07:42:49.948+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-12-11 07:42:35.121505+00:00
[2022-12-11T07:42:50.016+0000] {standard_task_runner.py:55} INFO - Started process 72 to run task
[2022-12-11T07:42:50.102+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'manual__2022-12-11T07:42:35.121505+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp2n9g_3yy']
[2022-12-11T07:42:50.140+0000] {standard_task_runner.py:83} INFO - Job 9: Subtask checkfiles.check_weather_table
[2022-12-11T07:42:51.275+0000] {task_command.py:376} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-12-11T07:42:35.121505+00:00 [running]> on host 01c108b234e9
[2022-12-11T07:42:53.484+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-11T07:42:35.121505+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-12-11T07:42:35.121505+00:00
[2022-12-11T07:42:53.495+0000] {mysql.py:84} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-12-11T07:42:53.699+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 86, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/hooks/sql.py", line 288, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 165, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 70, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 432, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_solar` isn't defined
[2022-12-11T07:42:53.765+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221211T074235, start_date=20221211T074249, end_date=20221211T074253
[2022-12-11T07:42:53.910+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 9 for task checkfiles.check_weather_table (The conn_id `mysql_solar` isn't defined; 72)
[2022-12-11T07:42:53.980+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2022-12-11T07:42:54.475+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
