[2022-12-09 10:35:44,912] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:35:45,012] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:35:45,014] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:35:45,015] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 10:35:45,016] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:35:45,116] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-12-08 00:00:00+00:00
[2022-12-09 10:35:45,135] {standard_task_runner.py:52} INFO - Started process 64 to run task
[2022-12-09 10:35:45,161] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpzswy2az6', '--error-file', '/tmp/tmpdm5124xr']
[2022-12-09 10:35:45,167] {standard_task_runner.py:80} INFO - Job 3: Subtask checkfiles.check_weather_table
[2022-12-09 10:35:45,251] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-09 10:35:45,505] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 10:35:46,063] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T00:00:00+00:00
[2022-12-09 10:35:46,068] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-12-09 10:35:46,231] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/operators/mysql.py", line 84, in execute
    hook.run(self.sql, autocommit=self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/mysql/hooks/mysql.py", line 158, in get_conn
    conn = self.connection or self.get_connection(getattr(self, self.conn_name_attr))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `mysql_solar` isn't defined
[2022-12-09 10:35:46,254] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221208T000000, start_date=20221209T103544, end_date=20221209T103546
[2022-12-09 10:35:46,319] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task checkfiles.check_weather_table (The conn_id `mysql_solar` isn't defined; 64)
[2022-12-09 10:35:46,347] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-12-09 10:35:46,796] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-09 10:40:59,451] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:40:59,501] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 10:40:59,502] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:40:59,503] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 10:40:59,505] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 10:40:59,574] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-12-08 00:00:00+00:00
[2022-12-09 10:40:59,589] {standard_task_runner.py:52} INFO - Started process 110 to run task
[2022-12-09 10:40:59,605] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp_w61vdeo', '--error-file', '/tmp/tmpc079j4e5']
[2022-12-09 10:40:59,609] {standard_task_runner.py:80} INFO - Job 16: Subtask checkfiles.check_weather_table
[2022-12-09 10:40:59,691] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-09 10:40:59,900] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 10:41:00,639] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T00:00:00+00:00
[2022-12-09 10:41:00,645] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-12-09 10:41:00,706] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-12-09 10:41:00,839] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-12-09 10:41:00,852] {dbapi.py:216} INFO - Rows affected: 0
[2022-12-09 10:41:01,056] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221208T000000, start_date=20221209T104059, end_date=20221209T104101
[2022-12-09 10:41:01,186] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-09 10:41:01,536] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-12-09 11:20:29,722] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 11:20:29,766] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [queued]>
[2022-12-09 11:20:29,768] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 11:20:29,769] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-12-09 11:20:29,770] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-12-09 11:20:29,862] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-12-08 00:00:00+00:00
[2022-12-09 11:20:29,884] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2022-12-09 11:20:29,904] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-12-08T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp8usbfyha', '--error-file', '/tmp/tmpkevvd6x9']
[2022-12-09 11:20:29,909] {standard_task_runner.py:80} INFO - Job 45: Subtask checkfiles.check_weather_table
[2022-12-09 11:20:29,998] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-12-09 11:20:30,214] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-12-08T00:00:00+00:00 [running]> on host 4d9af2ba34e6
[2022-12-09 11:20:31,087] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-12-08T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-12-08T00:00:00+00:00
[2022-12-09 11:20:31,094] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-12-09 11:20:31,143] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-12-09 11:20:31,274] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-12-09 11:20:31,291] {dbapi.py:216} INFO - Rows affected: 0
[2022-12-09 11:20:31,375] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221208T000000, start_date=20221209T112029, end_date=20221209T112031
[2022-12-09 11:20:31,462] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-12-09 11:20:31,736] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
