[2022-11-20 11:54:25,531] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-11-20T11:54:23.782139+00:00 [queued]>
[2022-11-20 11:54:25,543] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-11-20T11:54:23.782139+00:00 [queued]>
[2022-11-20 11:54:25,544] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-20 11:54:25,544] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-20 11:54:25,545] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-20 11:54:25,563] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-20 11:54:23.782139+00:00
[2022-11-20 11:54:25,568] {standard_task_runner.py:52} INFO - Started process 274 to run task
[2022-11-20 11:54:25,572] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'manual__2022-11-20T11:54:23.782139+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpc27s_ylt', '--error-file', '/tmp/tmpnakn4682']
[2022-11-20 11:54:25,574] {standard_task_runner.py:80} INFO - Job 65: Subtask checkfiles.check_weather_table
[2022-11-20 11:54:25,654] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table manual__2022-11-20T11:54:23.782139+00:00 [running]> on host 82103fd5e777
[2022-11-20 11:54:25,792] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T11:54:23.782139+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-20T11:54:23.782139+00:00
[2022-11-20 11:54:25,793] {mysql.py:82} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location));
                
[2022-11-20 11:54:25,809] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-20 11:54:25,836] {dbapi.py:208} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location));
                , parameters: None
[2022-11-20 11:54:25,842] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-20 11:54:25,869] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221120T115423, start_date=20221120T115425, end_date=20221120T115425
[2022-11-20 11:54:25,905] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-20 11:54:25,986] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
