[2022-11-22 05:06:29,842] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:06:13.071295+00:00 [queued]>
[2022-11-22 05:06:29,890] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:06:13.071295+00:00 [queued]>
[2022-11-22 05:06:29,891] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:06:29,893] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 05:06:29,894] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 05:06:29,960] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): load_files.extract_geography_info> on 2022-11-22 05:06:13.071295+00:00
[2022-11-22 05:06:29,977] {standard_task_runner.py:52} INFO - Started process 445 to run task
[2022-11-22 05:06:29,990] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'load_files.extract_geography_info', 'manual__2022-11-22T05:06:13.071295+00:00', '--job-id', '228', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpxhl9ybz5', '--error-file', '/tmp/tmpfz_3t6e_']
[2022-11-22 05:06:29,995] {standard_task_runner.py:80} INFO - Job 228: Subtask load_files.extract_geography_info
[2022-11-22 05:06:30,308] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.load_files.extract_geography_info manual__2022-11-22T05:06:13.071295+00:00 [running]> on host 8a647070b091
[2022-11-22 05:06:30,750] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=load_files.extract_geography_info
AIRFLOW_CTX_EXECUTION_DATE=2022-11-22T05:06:13.071295+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-22T05:06:13.071295+00:00
[2022-11-22 05:06:30,853] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 05:06:31,025] {python.py:173} INFO - Done. Returned value was: None
[2022-11-22 05:06:31,087] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=load_files.extract_geography_info, execution_date=20221122T050613, start_date=20221122T050629, end_date=20221122T050631
[2022-11-22 05:06:31,175] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 05:06:31,442] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
