[2022-11-22 02:59:30,038] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 02:59:30,158] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 02:59:30,177] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 02:59:30,187] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 02:59:30,192] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 02:59:30,407] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 02:59:30,427] {standard_task_runner.py:52} INFO - Started process 60 to run task
[2022-11-22 02:59:30,453] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmph2qh39nh', '--error-file', '/tmp/tmp97_5v1s_']
[2022-11-22 02:59:30,460] {standard_task_runner.py:80} INFO - Job 74: Subtask checkfiles.check_solar_table
[2022-11-22 02:59:30,613] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 02:59:30,931] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 02:59:31,447] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 02:59:31,456] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 02:59:31,505] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 02:59:32,050] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 02:59:32,114] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 02:59:32,302] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T025930, end_date=20221122T025932
[2022-11-22 02:59:32,527] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 02:59:33,087] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:03:27,095] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:03:27,146] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:03:27,147] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:27,149] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:03:27,150] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:27,216] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:03:27,227] {standard_task_runner.py:52} INFO - Started process 72 to run task
[2022-11-22 03:03:27,242] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp76jizs6d', '--error-file', '/tmp/tmpjpc49rg_']
[2022-11-22 03:03:27,245] {standard_task_runner.py:80} INFO - Job 77: Subtask checkfiles.check_solar_table
[2022-11-22 03:03:27,297] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:03:27,499] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:03:27,857] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:03:27,860] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 03:03:27,902] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:03:28,027] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 03:03:28,042] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:03:28,134] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T030327, end_date=20221122T030328
[2022-11-22 03:03:28,220] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:03:28,381] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:06:33,505] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:06:33,570] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:06:33,572] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:06:33,573] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:06:33,574] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:06:33,648] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:06:33,661] {standard_task_runner.py:52} INFO - Started process 98 to run task
[2022-11-22 03:06:33,673] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmphs3dkt3f', '--error-file', '/tmp/tmpuw2iadsi']
[2022-11-22 03:06:33,675] {standard_task_runner.py:80} INFO - Job 88: Subtask checkfiles.check_solar_table
[2022-11-22 03:06:33,730] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:06:33,891] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:06:34,395] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:06:34,404] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 03:06:34,497] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:06:34,615] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 03:06:34,642] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:06:34,822] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T030633, end_date=20221122T030634
[2022-11-22 03:06:34,947] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:06:35,409] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:09:13,327] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:09:13,426] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:09:13,429] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:13,433] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:09:13,436] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:13,589] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:09:13,614] {standard_task_runner.py:52} INFO - Started process 149 to run task
[2022-11-22 03:09:13,637] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp35o1uinp', '--error-file', '/tmp/tmp4il066_a']
[2022-11-22 03:09:13,640] {standard_task_runner.py:80} INFO - Job 105: Subtask checkfiles.check_solar_table
[2022-11-22 03:09:13,715] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:09:13,975] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:09:14,422] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:09:14,426] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 03:09:14,493] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:09:14,642] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 03:09:14,667] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:09:14,796] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T030913, end_date=20221122T030914
[2022-11-22 03:09:14,956] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:09:15,197] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:12:51,566] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:12:51,610] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:12:51,612] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:12:51,613] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:12:51,614] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:12:51,684] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:12:51,696] {standard_task_runner.py:52} INFO - Started process 172 to run task
[2022-11-22 03:12:51,710] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpsve8kcta', '--error-file', '/tmp/tmpcyjug4gr']
[2022-11-22 03:12:51,712] {standard_task_runner.py:80} INFO - Job 112: Subtask checkfiles.check_solar_table
[2022-11-22 03:12:51,764] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:12:51,939] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:12:52,306] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:12:52,308] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 03:12:52,378] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:12:52,468] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 03:12:52,482] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:12:52,550] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T031251, end_date=20221122T031252
[2022-11-22 03:12:52,615] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:12:52,806] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:00:19,902] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:00:19,972] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:00:19,974] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:00:19,976] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:00:19,978] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:00:20,063] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:00:20,078] {standard_task_runner.py:52} INFO - Started process 64 to run task
[2022-11-22 04:00:20,095] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp6cb2twxh', '--error-file', '/tmp/tmppd4298ay']
[2022-11-22 04:00:20,100] {standard_task_runner.py:80} INFO - Job 123: Subtask checkfiles.check_solar_table
[2022-11-22 04:00:20,171] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:00:20,397] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:00:20,836] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:00:20,839] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 04:00:20,894] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:00:21,088] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 04:00:21,113] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:00:21,199] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T040019, end_date=20221122T040021
[2022-11-22 04:00:21,320] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:00:21,581] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:02:21,668] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:02:21,731] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:02:21,733] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:02:21,738] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:02:21,739] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:02:21,850] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:02:21,876] {standard_task_runner.py:52} INFO - Started process 118 to run task
[2022-11-22 04:02:21,910] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '138', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpelcbok8c', '--error-file', '/tmp/tmp0fq4yj0r']
[2022-11-22 04:02:21,916] {standard_task_runner.py:80} INFO - Job 138: Subtask checkfiles.check_solar_table
[2022-11-22 04:02:22,023] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:02:22,318] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:02:22,908] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:02:22,921] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 04:02:22,976] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:02:23,108] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 04:02:23,130] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:02:23,335] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T040221, end_date=20221122T040223
[2022-11-22 04:02:23,421] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:02:23,688] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:12:41,646] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:12:41,716] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:12:41,721] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:12:41,723] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:12:41,725] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:12:41,872] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:12:41,941] {standard_task_runner.py:52} INFO - Started process 170 to run task
[2022-11-22 04:12:41,966] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmps1bz7ndi', '--error-file', '/tmp/tmpkjrkbfzz']
[2022-11-22 04:12:41,973] {standard_task_runner.py:80} INFO - Job 149: Subtask checkfiles.check_solar_table
[2022-11-22 04:12:42,090] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:12:42,498] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:12:43,014] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:12:43,021] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 04:12:43,074] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:12:43,232] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 04:12:43,251] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:12:43,413] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T041241, end_date=20221122T041243
[2022-11-22 04:12:43,624] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:12:43,968] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:44:24,907] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:24,976] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:24,977] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:24,979] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:44:24,980] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:25,108] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_solar_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:44:25,123] {standard_task_runner.py:52} INFO - Started process 219 to run task
[2022-11-22 04:44:25,138] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_solar_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '166', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp_yvwdmhu', '--error-file', '/tmp/tmpj0msqb4e']
[2022-11-22 04:44:25,143] {standard_task_runner.py:80} INFO - Job 166: Subtask checkfiles.check_solar_table
[2022-11-22 04:44:25,249] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:44:25,574] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_solar_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:44:26,069] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_solar_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:44:26,072] {mysql.py:82} INFO - Executing: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location))
[2022-11-22 04:44:26,116] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:44:26,262] {dbapi.py:208} INFO - Running statement: 


CREATE TABLE IF NOT EXISTS geography(
                locdate VARCHAR(40),
                location VARCHAR(40),
                updated_date CHAR(10),
                altitudeMeridian VARCHAR(13),
                altitude_09 VARCHAR(20),
                altitude_12 VARCHAR(20),
                altitude_15 VARCHAR(20),
                altitude_18 VARCHAR(20),
                azimuth_09 VARCHAR(20),
                azimuth_12 VARCHAR(20),
                azimuth_15 VARCHAR(20),
                azimuth_18 VARCHAR(20),
                primary key(locdate,location)), parameters: None
[2022-11-22 04:44:26,281] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:44:26,481] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_solar_table, execution_date=20221121T000000, start_date=20221122T044424, end_date=20221122T044426
[2022-11-22 04:44:26,653] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:44:26,954] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
