[2022-11-22 02:59:30,580] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 02:59:30,691] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 02:59:30,694] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 02:59:30,696] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 02:59:30,698] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 02:59:30,850] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 02:59:30,871] {standard_task_runner.py:52} INFO - Started process 61 to run task
[2022-11-22 02:59:30,887] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '73', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp4aueiryj', '--error-file', '/tmp/tmpg9e7dkkb']
[2022-11-22 02:59:30,890] {standard_task_runner.py:80} INFO - Job 73: Subtask checkfiles.check_weather_table
[2022-11-22 02:59:30,962] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 02:59:31,266] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 02:59:32,293] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 02:59:32,295] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 02:59:32,402] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 02:59:32,610] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 02:59:32,649] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 02:59:32,893] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T025930, end_date=20221122T025932
[2022-11-22 02:59:33,050] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 02:59:33,267] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:03:27,619] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:03:27,664] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:03:27,665] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:27,666] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:03:27,667] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:03:27,735] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:03:27,747] {standard_task_runner.py:52} INFO - Started process 75 to run task
[2022-11-22 03:03:27,764] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmppns1o30r', '--error-file', '/tmp/tmp6so5zpi6']
[2022-11-22 03:03:27,766] {standard_task_runner.py:80} INFO - Job 80: Subtask checkfiles.check_weather_table
[2022-11-22 03:03:27,823] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:03:28,028] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:03:28,408] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:03:28,411] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 03:03:28,461] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:03:28,561] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 03:03:28,581] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:03:28,656] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T030327, end_date=20221122T030328
[2022-11-22 03:03:28,718] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:03:28,906] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:06:34,058] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:06:34,120] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:06:34,123] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:06:34,124] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:06:34,125] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:06:34,236] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:06:34,255] {standard_task_runner.py:52} INFO - Started process 101 to run task
[2022-11-22 03:06:34,271] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '89', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmprl5lfcbw', '--error-file', '/tmp/tmpyundr011']
[2022-11-22 03:06:34,274] {standard_task_runner.py:80} INFO - Job 89: Subtask checkfiles.check_weather_table
[2022-11-22 03:06:34,341] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:06:34,606] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:06:35,456] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:06:35,470] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 03:06:35,585] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:06:35,802] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 03:06:35,821] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:06:35,982] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T030634, end_date=20221122T030635
[2022-11-22 03:06:36,234] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:06:36,597] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:09:12,446] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:09:12,520] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:09:12,522] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:12,523] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:09:12,524] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:09:12,605] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:09:12,621] {standard_task_runner.py:52} INFO - Started process 146 to run task
[2022-11-22 03:09:12,633] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp0u9lsxuy', '--error-file', '/tmp/tmpz5olehzn']
[2022-11-22 03:09:12,636] {standard_task_runner.py:80} INFO - Job 102: Subtask checkfiles.check_weather_table
[2022-11-22 03:09:12,708] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:09:12,982] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:09:13,622] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:09:13,627] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 03:09:13,679] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:09:13,792] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 03:09:13,810] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:09:13,892] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T030912, end_date=20221122T030913
[2022-11-22 03:09:13,963] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:09:14,139] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 03:12:51,730] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:12:51,777] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 03:12:51,779] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:12:51,780] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 03:12:51,782] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 03:12:51,845] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 03:12:51,856] {standard_task_runner.py:52} INFO - Started process 173 to run task
[2022-11-22 03:12:51,868] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '114', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpozz1jlbe', '--error-file', '/tmp/tmpsw1vx50_']
[2022-11-22 03:12:51,870] {standard_task_runner.py:80} INFO - Job 114: Subtask checkfiles.check_weather_table
[2022-11-22 03:12:51,925] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 03:12:52,125] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 42206527e50b
[2022-11-22 03:12:52,526] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 03:12:52,528] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 03:12:52,577] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 03:12:52,681] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 03:12:52,698] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 03:12:52,812] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T031251, end_date=20221122T031252
[2022-11-22 03:12:52,901] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 03:12:53,072] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:00:20,297] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:00:20,357] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:00:20,358] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:00:20,360] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:00:20,361] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:00:20,442] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:00:20,458] {standard_task_runner.py:52} INFO - Started process 66 to run task
[2022-11-22 04:00:20,479] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmp7dd74hcf', '--error-file', '/tmp/tmpptat9zip']
[2022-11-22 04:00:20,484] {standard_task_runner.py:80} INFO - Job 122: Subtask checkfiles.check_weather_table
[2022-11-22 04:00:20,553] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:00:20,771] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:00:21,234] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:00:21,238] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 04:00:21,292] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:00:21,407] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 04:00:21,425] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:00:21,723] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T040020, end_date=20221122T040021
[2022-11-22 04:00:21,836] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:00:22,061] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:02:21,064] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:02:21,115] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:02:21,116] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:02:21,117] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:02:21,118] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:02:21,199] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:02:21,214] {standard_task_runner.py:52} INFO - Started process 114 to run task
[2022-11-22 04:02:21,240] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpamacsptn', '--error-file', '/tmp/tmpjl0zv838']
[2022-11-22 04:02:21,245] {standard_task_runner.py:80} INFO - Job 135: Subtask checkfiles.check_weather_table
[2022-11-22 04:02:21,309] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:02:21,514] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:02:22,292] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:02:22,296] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 04:02:22,390] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:02:22,518] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 04:02:22,535] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:02:22,627] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T040221, end_date=20221122T040222
[2022-11-22 04:02:22,778] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:02:23,123] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:12:41,927] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:12:42,045] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:12:42,049] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:12:42,051] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:12:42,056] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:12:42,228] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:12:42,249] {standard_task_runner.py:52} INFO - Started process 172 to run task
[2022-11-22 04:12:42,296] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '151', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmpnohf8ypv', '--error-file', '/tmp/tmpmp5vo5yj']
[2022-11-22 04:12:42,319] {standard_task_runner.py:80} INFO - Job 151: Subtask checkfiles.check_weather_table
[2022-11-22 04:12:42,480] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:12:42,854] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:12:43,726] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:12:43,735] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 04:12:43,805] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:12:43,936] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 04:12:43,961] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:12:44,054] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T041241, end_date=20221122T041244
[2022-11-22 04:12:44,130] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:12:44,356] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-11-22 04:44:24,703] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:24,754] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2022-11-22 04:44:24,755] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:24,757] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-11-22 04:44:24,758] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-22 04:44:24,846] {taskinstance.py:1377} INFO - Executing <Task(MySqlOperator): checkfiles.check_weather_table> on 2022-11-21 00:00:00+00:00
[2022-11-22 04:44:24,868] {standard_task_runner.py:52} INFO - Started process 218 to run task
[2022-11-22 04:44:24,893] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'etl_solar', 'checkfiles.check_weather_table', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/dag_preprocess.py', '--cfg-path', '/tmp/tmppdna2m6z', '--error-file', '/tmp/tmpwi066p6d']
[2022-11-22 04:44:24,899] {standard_task_runner.py:80} INFO - Job 164: Subtask checkfiles.check_weather_table
[2022-11-22 04:44:24,990] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/configuration.py:470: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  option = self._get_environment_variables(deprecated_key, deprecated_section, key, section)

[2022-11-22 04:44:25,264] {task_command.py:369} INFO - Running <TaskInstance: etl_solar.checkfiles.check_weather_table scheduled__2022-11-21T00:00:00+00:00 [running]> on host 8a647070b091
[2022-11-22 04:44:25,872] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=etl_solar
AIRFLOW_CTX_TASK_ID=checkfiles.check_weather_table
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2022-11-22 04:44:25,874] {mysql.py:82} INFO - Executing: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location))
[2022-11-22 04:44:25,926] {base.py:68} INFO - Using connection ID 'mysql_solar' for task execution.
[2022-11-22 04:44:26,026] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS weather_info(
                locdatetime VARCHAR(40),
                location VARCHAR(40),
                updated_date VARCHAR(13),
                temperature FLOAT,
                precipitation_form FLOAT,
                precipitation_prob FLOAT,
                humidity FLOAT,
                wind_speed FLOAT,
                wind_direction FLOAT,
                cloud FLOAT,
                primary key(locdatetime,location)), parameters: None
[2022-11-22 04:44:26,044] {dbapi.py:216} INFO - Rows affected: 0
[2022-11-22 04:44:26,125] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=etl_solar, task_id=checkfiles.check_weather_table, execution_date=20221121T000000, start_date=20221122T044424, end_date=20221122T044426
[2022-11-22 04:44:26,216] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-11-22 04:44:26,788] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
